apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{   .Values.name  }}
  namespace: {{.Values.namespace}}
  labels:
    {{- toYaml .Values.labels.deployment | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      {{- toYaml .Values.labels.pod | nindent 6}}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- toYaml .Values.labels.pod | nindent 8}}
    spec:
      containers:
        - name: {{.Values.name}}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port}}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-cm
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
    {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- range .}}
        {{ .labelKey | quote }}: {{ .labelVal | quote }}
      {{- end }}
    {{- end }} 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.labels.pod.app }}
              topologyKey: "kubernetes.io/hostname"
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}

    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}